# Generated by Django 4.1.4 on 2022-12-16 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stream_key', models.CharField(default='4nZmRBG9ZDio8dBHyJL2A2imZ98Qk7mPRWM7XQGedBNH', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(default='Not given', on_delete=django.db.models.deletion.SET_DEFAULT, to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stream.videostream')),
            ],
        ),
    ]
